### PR TITLE
提示db thread except:(2003, "Can't connect to MySQL server on 'localhost' (110)")

### PR DESCRIPTION
**Pull request by oovz**
RT...
而且已经到sleep9999了...

### CODE REVIEW

**Comment by mengskysama** [comment]
use `mysql -h localhost -P 3306 -u root -p123456` should encounter the same error.
I think that may be the database is not configured correctly

**Comment by oovz** [comment]
pma都正常...
不会是mysql的事吧

**Comment by instylecool** [comment]
我也遇到了。。。系统都换了还是一样。

**Comment by oovz** [comment]
@instylecool 直接装mysql，别用各种集成脚本

**Comment by instylecool** [comment]
@mikaoras 好的我试试

**Pull request closed without merging**
